workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - when: always

variables:
  DOCKER_REGISTRY: docker.io/wearestancer
  VERSION: 3.12

.python::base:
  image: ${DOCKER_REGISTRY}/python:$VERSION-uv
  before_script:
    - uv --version
    - python --version
    - uv venv
    - uv sync

pylint:
  extends: .python::base

  script:
    - uv run pylint ./stancer/ ./tests/

bandit:
  extends: .python::base

  script:
    - uv run bandit ./stancer/ -r

pytest:
  extends: .python::base

  script:
    - uv run pytest --cov-report term-missing --cov-report xml:cobertura.xml --junitxml=junit.xml ./stancer/

ruff:
  extends: .python::base

  script:
    - uv ruff check
