stages:
  - lint
  - test

workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - when: always

variables:
  DOCKER_REGISTRY: docker.io/wearestancer
  VERSION: 3.12

.python::base:
  image: ${DOCKER_REGISTRY}/python:$VERSION-uv
  before_script:
    - uv --version
    - python --version
    - uv sync --locked
    - uv tree

.python::current-versions:
  extends:
    - .python::base
  parallel:
    matrix:
      - VERSION:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

pylint:
  extends: .python::base

  stage: lint

  script:
    - uv add pylint-gitlab pylint-quotes
    - uv run pylint --output-format=pylint_gitlab.GitlabCodeClimateReporter:codequality.json,text --reports=y --score=y ${PYLINT_TARGET:-.}
  artifacts:
    reports:
      codequality: codequality.json

bandit:
  extends: .python::base

  stage: lint

  script:
    - uv run bandit --exit-zero --configfile pyproject.toml --recursive ${BANDIT_TARGET:-.}
    - uv run bandit --configfile pyproject.toml --format json --output results.json --recursive ${BANDIT_TARGET:-.}

  artifacts:
    reports:
      codequality: results.json

pytest:
  extends: .python::current-versions

  stage: test

  script:
    - uv run pytest --cov-report term-missing --cov-report xml:cobertura.xml --junitxml=junit.xml .

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
      junit: junit.xml

ruff:
  extends: .python::base

  stage: lint

  script:
    - uv run ruff --version
    - uv run ruff check --exit-zero
    - uv run ruff format
    - uv run ruff check --output-format=gitlab > ruff-report.json

  artifacts:
    reports:
      codequality: ruff-report.json

mypy:
  extends: .python::base

  stage: lint
  script:
    - uv run mypy . --pretty --cobertura-xml-report ./ --junit-xml junit.xml

  allow_failure: true # This job is just indicative for now.
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
      junit: junit.xml
