workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - when: always

variables:
  DOCKER_REGISTRY: docker.io/wearestancer
  VERSION: 3.12

.python::base:
  image: ${DOCKER_REGISTRY}/python:$VERSION-uv
  before_script:
    - uv --version
    - python --version
    - uv sync
    - uv tree

pylint:
  extends: .python::base

  script:
    - uv add pylint-gitlab pylint-quotes
    - uv run pylint --output-format=pylint_gitlab.GitlabCodeClimateReporter:codequality.json,text \
      --reports=y --score=y ${PYLINT_TARGET:-.}
  artifacts:
    reports:
      codequality: codequality.json

bandit:
  extends: .python::base

  script:
    - uv run bandit --exit-zero --configfile .bandit.yml --recursive ${BANDIT_TARGET:-.}
    - uv run bandit --exit-zero --configfile .bandit.yml \
      --format json --output results.json \
      --recursive ${BANDIT_TARGET:-.}

  artifacts:
    reports:
      codequality: results.json

pytest:
  extends: .python::base

  script:
    - uv run pytest --cov-report term-missing --cov-report xml:cobertura.xml --junitxml=junit.xml ./stancer/

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
      junit: junit.xml

ruff:
  extends: .python::base

  script:
    - uv run ruff --version
    - uv run ruff check
    - uv run ruff check --output-format=gitlab > ruff-report.json

  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/ruff-report.json
